return {
  'folke/which-key.nvim',
  version = '^3.17',
  dependencies = { 'nvim-tree/nvim-web-devicons' },
  event = 'VeryLazy',
  lazy = false,
  opts = {
    preset = 'classic',
    delay = 800,
    win = { no_overlap = true },
    spec = {
      {
        '<leader>y',
        '"+y',
        mode = { 'n', 'v', 'x' },
        desc = 'Yank to the system clipboard',
        icon = { icon = '󰱗', color = 'yellow' },
        noremap = false,
      },
      {
        '<leader>Y',
        '"+Y',
        mode = { 'n', 'v', 'x' },
        desc = 'Yank [count] lines to the system clipboard',
        icon = { icon = '󰱗', color = 'yellow' },
        noremap = false,
      },
      {
        '<leader>d',
        '"+d',
        mode = { 'n', 'v', 'x' },
        desc = 'Cut to the system clipboard',
        icon = { icon = '', color = 'yellow' },
        noremap = false,
      },
      {
        '<leader>D',
        '"+D',
        mode = { 'n', 'v', 'x' },
        desc = 'Cut line until the end to the system clipboard',
        icon = { icon = '', color = 'yellow' },
        noremap = false,
      },
      {
        '<leader>?',
        function()
          require('which-key').show()
        end,
        mode = { 'n', 'v' },
        desc = 'Show keymaps',
        icon = { icon = '󰡾', color = 'yellow' },
      },
      {
        'gd',
        vim.lsp.buf.definition,
        mode = 'n',
        desc = 'Go to definition',
        icon = { icon = '', color = 'orange' },
      },
      {
        'gD',
        vim.lsp.buf.declaration,
        mode = 'n',
        desc = 'Go to declaration',
        icon = { icon = '', color = 'orange' },
      },
      {
        '<leader>fS',
        vim.lsp.buf.workspace_symbol,
        mode = 'n',
        desc = '[F]ind workspace [s]ymbols',
        icon = { icon = '󱊓', color = 'orange' },
      },
      {
        '<leader>fs',
        vim.lsp.buf.document_symbol,
        mode = 'n',
        desc = '[F]ind document [s]ymbols',
        icon = { icon = '󱊓', color = 'orange' },
      },
      {
        '<leader>lcr',
        vim.lsp.codelens.run,
        mode = 'n',
        desc = 'Run the [L]SP [c]odelens',
        icon = { icon = '󱖪', color = 'orange' },
      },
      {
        '<leader>lf',
        vim.lsp.buf.format,
        mode = 'n',
        desc = '[L]SP [f]ormat the document',
        icon = { icon = '', color = 'orange' },
      },
    },
  },
}
